# Generated by Django 5.2.5 on 2026-06-17 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='order_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Success'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
