# Generated by Django 5.2.5 on 2026-05-16 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_remove_subcategory_general_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='vantor',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_vendor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='shop_logo',
            field=models.ImageField(blank=True, null=True, upload_to='vendors/'),
        ),
    ]
